def on_forever():
    OLED.init(64, 128)
    OLED.write_string_new_line("Launching Debug Environment")
    OLED.write_string_new_line("←")
    basic.pause(25)
    OLED.write_string_new_line("→")
    basic.pause(25)
    OLED.write_string_new_line("")
    basic.pause(25)
    OLED.write_string_new_line("")
    basic.pause(25)
    OLED.write_string_new_line("")
    basic.pause(25)
    OLED.write_string_new_line("")
basic.forever(on_forever)
